### ISSUE TITLE
Collect config actions from the user.

### ISSUE THREAD

**Issue by kevinquillen** [kevinquillen/recipe-generator#1]
We need the ability to collect config actions as part of the generator.

Example:

```yaml
  actions:
    block.block.gin_admin:
      simple_config_update:
        status: false
    block.block.gin_branding:
      simple_config_update:
        status: false
    block.block.gin_local_actions:
      simple_config_update:
        region: content
        weight: -10
    block.block.gin_local_tasks:
      simple_config_update:
        status: false
    block.block.gin_page_title:
      simple_config_update:
        region: header
        weight: -10
    block.block.gin_primary_local_tasks:
      simple_config_update:
        region: header
        weight: -5
    block.block.gin_tools:
      simple_config_update:
        status: false
    node.settings:
      simple_config_update:
        use_admin_theme: true
    user.settings:
      simple_config_update:
        register: admin_only
```

Note that some actions have a string values, some have an array value, some have complex values (setComponent).

https://git.drupalcode.org/project/distributions_recipes/-/blob/1.0.x/docs/config_actions.md
